### ISSUE TITLE
[tracking issue] delta kernel write path

### ISSUE THREAD

**Issue by zachschuermann** [delta-incubator/delta-kernel-rs#377]
Tracking issue for write support in delta_kernel. Will be updating with PRs/links as we go!

- [ ] stage 0: blind append support
  - [ ] transaction/commit flow
  - [ ] data path
- [ ] stage 1: FFI (for blind append)
- [ ] stage 2: create table, checkpointing, and better conflict resolution
  - [ ] create table API
  - [ ] checkpointing API
  - [ ] conflict detection and automatic retries

**Comment by zachschuermann** [comment]
update for today: `create_one` API is in progress, hoping to finalize that in the coming weeks to unblock idempotent writes and CREATE TABLE.

**Comment by zachschuermann** [comment]
`create_one` PR landed: #662 and WIP PR for stats support: #787
